package jobsheet6;


import static java.lang.Double.parseDouble;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author M.  RAFI PUTRA
 */
public class Calculate extends javax.swing.JFrame {

    /**
     * Creates new form Calculate
     */
    Double input1,input2,hasil;
    public Calculate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBill1 = new javax.swing.JTextField();
        txtBill2 = new javax.swing.JTextField();
        txtHasil = new javax.swing.JTextField();
        btnPembagian = new javax.swing.JButton();
        btnPerkalian = new javax.swing.JButton();
        btnPenjumlahan = new javax.swing.JButton();
        btnPengurangan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bilangan 1 :");

        jLabel2.setText("Bilangan 2 :");

        jLabel3.setText("Hasil :");

        txtBill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBill2ActionPerformed(evt);
            }
        });

        btnPembagian.setText("/");
        btnPembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembagianActionPerformed(evt);
            }
        });

        btnPerkalian.setText("x");
        btnPerkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerkalianActionPerformed(evt);
            }
        });

        btnPenjumlahan.setText("+");
        btnPenjumlahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjumlahanActionPerformed(evt);
            }
        });

        btnPengurangan.setText("-");
        btnPengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenguranganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtHasil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(txtBill2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBill1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPenjumlahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerkalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPembagian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPembagian))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtBill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnPerkalian)
                        .addGap(24, 24, 24)
                        .addComponent(btnPenjumlahan)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPengurangan))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBill2ActionPerformed

    private void btnPembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembagianActionPerformed
        // TODO add your handling code here:
        input1=Double.parseDouble(this.txtBill1.getText());
        input2=Double.parseDouble(this.txtBill2.getText());
        hasil=input1/input2;
        this.txtHasil.setText(" = " + hasil);
        
    }//GEN-LAST:event_btnPembagianActionPerformed

    private void btnPerkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerkalianActionPerformed
        // TODO add your handling code here:
        input1=Double.parseDouble(this.txtBill1.getText());
        input2=Double.parseDouble(this.txtBill2.getText());
        hasil=input1*input2;
        this.txtHasil.setText(" = " + hasil);
    }//GEN-LAST:event_btnPerkalianActionPerformed

    private void btnPenjumlahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjumlahanActionPerformed
        // TODO add your handling code here:
        input1=Double.parseDouble(this.txtBill1.getText());
        input2=Double.parseDouble(this.txtBill2.getText());
        hasil=input1+input2;
        this.txtHasil.setText(" = " + hasil);
    }//GEN-LAST:event_btnPenjumlahanActionPerformed

    private void btnPenguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenguranganActionPerformed
        // TODO add your handling code here:
        input1=Double.parseDouble(this.txtBill1.getText());
        input2=Double.parseDouble(this.txtBill2.getText());
        hasil=input1-input2;
        this.txtHasil.setText(" = " + hasil);
    }//GEN-LAST:event_btnPenguranganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPembagian;
    private javax.swing.JButton btnPengurangan;
    private javax.swing.JButton btnPenjumlahan;
    private javax.swing.JButton btnPerkalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtBill1;
    private javax.swing.JTextField txtBill2;
    private javax.swing.JTextField txtHasil;
    // End of variables declaration//GEN-END:variables
}
